python change_fields.py --field_indx 0
python change_fields.py --field_indx 1
python change_fields.py --field_indx 2
python change_fields.py --field_indx 3
python change_fields.py --field_indx 4
python change_fields.py --field_indx 5
python change_fields.py --field_indx 6
python change_fields.py --field_indx 7
python change_fields.py --field_indx 8
python change_fields.py --field_indx 9
python change_fields.py --field_indx 10
python change_fields.py --field_indx 11
python change_fields.py --field_indx 12
python change_fields.py --field_indx 13
python change_fields.py --field_indx 14
python change_fields.py --field_indx 15
python change_fields.py --field_indx 16
python change_fields.py --field_indx 17
python change_fields.py --field_indx 18
python change_fields.py --field_indx 19
python change_fields.py --field_indx 20
python change_fields.py --field_indx 21
python change_fields.py --field_indx 22
python change_fields.py --field_indx 23
