python weather.py --cloud_offset_year 0
python weather.py --cloud_offset_year 10
python weather.py --cloud_offset_year 20
python weather.py --cloud_offset_year 30
python weather.py --cloud_offset_year 1
python weather.py --cloud_offset_year 11
python weather.py --cloud_offset_year 21
python weather.py --cloud_offset_year 31
python weather.py --cloud_offset_year 35
python weather.py --cloud_offset_year 36
