python weather2.py --cloud_offset_year 0
python weather2.py --cloud_offset_year 10
python weather2.py --cloud_offset_year 20
python weather2.py --cloud_offset_year 30
python weather2.py --cloud_offset_year 1
python weather2.py --cloud_offset_year 2
python weather2.py --cloud_offset_year 3
python weather2.py --cloud_offset_year 4
python weather2.py --cloud_offset_year 5
python weather2.py --cloud_offset_year 6
python weather2.py --cloud_offset_year 7
python weather2.py --cloud_offset_year 11
python weather2.py --cloud_offset_year 21
python weather2.py --cloud_offset_year 31
python weather2.py --cloud_offset_year 35
python weather2.py --cloud_offset_year 36
